package com.antiaction.zwave.constants;

public class Constants {

	public static final int ZWAVE_RESPONSE_TIMEOUT = 5000;		// 5000 ms ZWAVE_RESPONSE TIMEOUT

	public static final int ZWAVE_RECEIVE_TIMEOUT = 1000;		// 1000 ms ZWAVE_RECEIVE_TIMEOUT

	public static final int SOF = 0x01;
	public static final int ACK = 0x06;
	public static final int NAK = 0x15;
	public static final int CAN = 0x18;

	public static byte[] ackMsg = {(byte)ACK};

	/**
	 * BINARY SWITCH CONSTANTS
	 */
	int SWITCH_BINARY_SET = 0x01; //set a value

	public static final String INDENT = "                                   ";

	public static final int PKT_IDX_PACKET_TYPE = 0;
	public static final int PKT_IDX_PACKET_LEN = 1;
	public static final int PKT_IDX_MSG_TYPE = 2;
	public static final int PKT_IDX_COMMAND = 3;
	public static final int PKT_IDX_NODE_ID = 4;
	public static final int PKT_IDX_TYPE = 8;

	public static final int FUNCTION_REGISTERED_DEVICES = 0x02;
	public static final int FUNCTION_DEVICE_SUPPORT_CLASSES = 0x49;

/*
	COMMAND_CLASS_ALARM = 0x71,
			COMMAND_CLASS_APPLICATION_STATUS = 0x22,
			COMMAND_CLASS_ASSOCIATION = 0x85,
			COMMAND_CLASS_ASSOCIATION_COMMAND_CONFIGURATION = 0x9b,
			COMMAND_CLASS_ASSOCIATION_V2 = 0x85,
			COMMAND_CLASS_AV_CONTENT_DIRECTORY_MD = 0x95,
			COMMAND_CLASS_AV_CONTENT_SEARCH_MD = 0x97,
			COMMAND_CLASS_AV_RENDERER_STATUS = 150,
			COMMAND_CLASS_AV_TAGGING_MD = 0x99,
			COMMAND_CLASS_BASIC = 0x20,
			COMMAND_CLASS_BASIC_TARIFF_INFO = 0x36,
			COMMAND_CLASS_BASIC_WINDOW_COVERING = 80,
			COMMAND_CLASS_BATTERY = 0x80,
			COMMAND_CLASS_CHIMNEY_FAN = 0x2a,
			COMMAND_CLASS_CLIMATE_CONTROL_SCHEDULE = 70,
			COMMAND_CLASS_CLOCK = 0x81,
			COMMAND_CLASS_CONFIGURATION = 0x70,
			COMMAND_CLASS_CONFIGURATION_V2 = 0x70,
			COMMAND_CLASS_CONTROLLER_REPLICATION = 0x21,
			COMMAND_CLASS_DOOR_LOCK = 0x62,
			COMMAND_CLASS_ENERGY_PRODUCTION = 0x90,
			COMMAND_CLASS_FIRMWARE_UPDATE_MD = 0x7a,
			COMMAND_CLASS_FIRMWARE_UPDATE_MD_V2 = 0x7a,
			COMMAND_CLASS_GEOGRAPHIC_LOCATION = 140,
			COMMAND_CLASS_GROUPING_NAME = 0x7b,
			COMMAND_CLASS_HAIL = 130,
			COMMAND_CLASS_INDICATOR = 0x87,
			COMMAND_CLASS_IP_CONFIGURATION = 0x9a,
			COMMAND_CLASS_LANGUAGE = 0x89,
			COMMAND_CLASS_LOCK = 0x76,
			COMMAND_CLASS_MANUFACTURER_PROPRIETARY = 0x91,
			COMMAND_CLASS_MANUFACTURER_SPECIFIC = 0x72,
			COMMAND_CLASS_MARK = 0xef,
			COMMAND_CLASS_METER = 50,
			COMMAND_CLASS_METER_PULSE = 0x35,
			COMMAND_CLASS_MTP_WINDOW_COVERING = 0x51,
			COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION_V2 = 0x8e,
			COMMAND_CLASS_MULTI_CHANNEL_V2 = 0x60,
			COMMAND_CLASS_MULTI_CMD = 0x8f,
			COMMAND_CLASS_MULTI_INSTANCE = 0x60,
			COMMAND_CLASS_MULTI_INSTANCE_ASSOCIATION = 0x8e,
			COMMAND_CLASS_NO_OPERATION = 0,
			COMMAND_CLASS_NODE_NAMING = 0x77,
			COMMAND_CLASS_NON_INTEROPERABLE = 240,
			COMMAND_CLASS_POWERLEVEL = 0x73,
			COMMAND_CLASS_PROPRIETARY = 0x88,
			COMMAND_CLASS_PROTECTION = 0x75,
			COMMAND_CLASS_PROTECTION_V2 = 0x75,
			COMMAND_CLASS_REMOTE_ASSOCIATION = 0x7d,
			COMMAND_CLASS_REMOTE_ASSOCIATION_ACTIVATE = 0x7c,
			COMMAND_CLASS_SCENE_ACTIVATION = 0x2b,
			COMMAND_CLASS_SCENE_ACTUATOR_CONF = 0x2c,
			COMMAND_CLASS_SCENE_CONTROLLER_CONF = 0x2d,
			COMMAND_CLASS_SCREEN_ATTRIBUTES = 0x93,
			COMMAND_CLASS_SCREEN_ATTRIBUTES_V2 = 0x93,
			COMMAND_CLASS_SCREEN_MD = 0x92,
			COMMAND_CLASS_SCREEN_MD_V2 = 0x92,
			COMMAND_CLASS_SECURITY = 0x98,
			COMMAND_CLASS_SENSOR_ALARM = 0x9c,
			COMMAND_CLASS_SENSOR_BINARY = 0x30,
			COMMAND_CLASS_SENSOR_CONFIGURATION = 0x9e,
			COMMAND_CLASS_SENSOR_MULTILEVEL = 0x31,
			COMMAND_CLASS_SENSOR_MULTILEVEL_V2 = 0x31,
			COMMAND_CLASS_SENSOR_MULTILEVEL_V3 = 0x31,
			COMMAND_CLASS_SILENCE_ALARM = 0x9d,
			COMMAND_CLASS_SIMPLE_AV_CONTROL = 0x94,
			COMMAND_CLASS_SWITCH_ALL = 0x27,
			COMMAND_CLASS_SWITCH_BINARY = 0x25,
			COMMAND_CLASS_SWITCH_MULTILEVEL = 0x26,
			COMMAND_CLASS_SWITCH_MULTILEVEL_V2 = 0x26,
			COMMAND_CLASS_SWITCH_TOGGLE_BINARY = 40,
			COMMAND_CLASS_SWITCH_TOGGLE_MULTILEVEL = 0x29,
			COMMAND_CLASS_THERMOSTAT_FAN_MODE = 0x44,
			COMMAND_CLASS_THERMOSTAT_FAN_STATE = 0x45,
			COMMAND_CLASS_THERMOSTAT_HEATING = 0x38,
			COMMAND_CLASS_THERMOSTAT_MODE = 0x40,
			COMMAND_CLASS_THERMOSTAT_MODE_V2 = 0x40,
			COMMAND_CLASS_THERMOSTAT_OPERATING_STATE = 0x42,
			COMMAND_CLASS_THERMOSTAT_SETBACK = 0x47,
			COMMAND_CLASS_THERMOSTAT_SETPOINT = 0x43,
			COMMAND_CLASS_THERMOSTAT_SETPOINT_V2 = 0x43,
			COMMAND_CLASS_TIME = 0x8a,
			COMMAND_CLASS_TIME_PARAMETERS = 0x8b,
			COMMAND_CLASS_TIME_V2 = 0x8a,
			COMMAND_CLASS_USER_CODE = 0x63,
			COMMAND_CLASS_VERSION = 0x86,
			COMMAND_CLASS_WAKE_UP = 0x84,
			COMMAND_CLASS_WAKE_UP_V2 = 0x84,
			COMMAND_CLASS_ZIP_ADV_CLIENT = 0x34,
			COMMAND_CLASS_ZIP_ADV_SERVER = 0x33,
			COMMAND_CLASS_ZIP_ADV_SERVICES = 0x2f,
			COMMAND_CLASS_ZIP_CLIENT = 0x2e,
			COMMAND_CLASS_ZIP_SERVER = 0x24,
			COMMAND_CLASS_ZIP_SERVICES = 0x23,
			ZWAVE_CMD_CLASS = 1
*/
}
